
name: Test

on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/test.yml'
      - 'index.js'
      - 'conf/*'
      - 'hooks/*'



concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  test:
    strategy:
      matrix:
        release: [ "8.0", "8.1", "8.2", "9.0", "9.1", "9.2", ""]
    runs-on: macos-12
    name: A job to run test NetBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@main
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          pkg_add curl
        mem: 2048
        copyback: false
        release: ${{ matrix.release }}
        nat: |
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        run: |
          pwd
          ls -lah
          whoami
          env
